import type { AnalysisResult } from "@/lib/analysis-schema";

export type { RiskLevel, Clause, AnalysisResult } from "@/lib/analysis-schema";

export const MOCK_ANALYSIS: AnalysisResult = {
  serviceName: "Instagram",
  fairnessScore: 38,
  verdict: "Unfair",
  totalClauses: 24,
  highRiskCount: 8,
  mediumRiskCount: 9,
  lowRiskCount: 7,
  clauses: [
    {
      id: "c1",
      number: "4.2.1",
      originalText: "By using the Service, you grant us a non-exclusive, royalty-free, transferable, sub-licensable, worldwide license to host, use, distribute, modify, run, copy, publicly perform or display, translate, and create derivative works of your content.",
      simplifiedText: "You give us permission to use anything you post in almost any way we want, for free, forever, and we can let others do the same.",
      explanation: "This is an extremely broad content license. Once you post something, the company can reuse, modify, and redistribute your content without paying you or asking permission.",
      riskLevel: "high",
      category: "Content Rights",
    },
    {
      id: "c2",
      number: "6.1.3",
      originalText: "We may collect information about the people, pages, accounts, hashtags and groups that you are connected to and how you interact with them across our Products.",
      simplifiedText: "We track everyone you interact with and how you use the app across all our products.",
      explanation: "This clause allows comprehensive social graph monitoring — not just what you do, but who you know and how you interact with them.",
      riskLevel: "high",
      category: "Data Collection",
    },
    {
      id: "c3",
      number: "7.4.2",
      originalText: "We reserve the right to remove any content or information you share on the Service if we believe that it violates these Terms of Use, our policies, or we are required to do so by law.",
      simplifiedText: "We can delete your content at any time if we think it breaks our rules.",
      explanation: "Broad content removal authority with subjective enforcement criteria. 'We believe' gives the company wide discretion.",
      riskLevel: "medium",
      category: "Content Moderation",
    },
    {
      id: "c4",
      number: "8.1.1",
      originalText: "You agree that any claim or dispute arising out of or relating to these Terms or the Service shall be resolved by binding arbitration, rather than in court.",
      simplifiedText: "If you have a legal dispute with us, you cannot sue us in court — you must use private arbitration.",
      explanation: "Forced arbitration removes your right to a jury trial and class action lawsuits, which typically favors the company.",
      riskLevel: "high",
      category: "Dispute Resolution",
    },
    {
      id: "c5",
      number: "3.2.1",
      originalText: "The Service is provided on an 'as is' and 'as available' basis without warranties of any kind, whether express or implied.",
      simplifiedText: "We don't guarantee the service will work properly or be available when you need it.",
      explanation: "Complete liability waiver — if the service breaks or loses your data, the company bears no legal responsibility.",
      riskLevel: "high",
      category: "Liability",
    },
    {
      id: "c6",
      number: "5.3.1",
      originalText: "We may share information about you with third-party partners for advertising purposes, including advertisers and measurement companies.",
      simplifiedText: "We share your data with advertisers and companies that measure ad performance.",
      explanation: "Your personal data is shared with third parties for targeted advertising. You have limited control over who receives this data.",
      riskLevel: "high",
      category: "Data Sharing",
    },
    {
      id: "c7",
      number: "2.1.4",
      originalText: "We may update these Terms from time to time. If we make changes, we will notify you by revising the date at the top of this policy.",
      simplifiedText: "We can change these rules whenever we want. We'll just update the date at the top of the page.",
      explanation: "Terms can change with minimal notice. Simply updating a date is easy to miss — you're responsible for checking.",
      riskLevel: "medium",
      category: "Terms Changes",
    },
    {
      id: "c8",
      number: "9.1.2",
      originalText: "We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever.",
      simplifiedText: "We can delete your account at any time, for any reason, without warning.",
      explanation: "Unilateral termination without cause or notice. You could lose access to your data and content without recourse.",
      riskLevel: "high",
      category: "Termination",
    },
    {
      id: "c9",
      number: "5.1.2",
      originalText: "We use the information we collect to provide, personalize, and improve our Products, including ads.",
      simplifiedText: "We use your data to customize the app and show you targeted ads.",
      explanation: "Data collection is tied to ad personalization. Your usage patterns directly fuel the advertising engine.",
      riskLevel: "medium",
      category: "Data Usage",
    },
    {
      id: "c10",
      number: "3.4.1",
      originalText: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
      simplifiedText: "You're responsible for keeping your password safe and everything that happens on your account.",
      explanation: "Standard security responsibility clause. Reasonable but means you bear the risk if your account is compromised.",
      riskLevel: "low",
      category: "Account Security",
    },
    {
      id: "c11",
      number: "1.2.1",
      originalText: "You must be at least 13 years old to use the Service.",
      simplifiedText: "You must be at least 13 to use this service.",
      explanation: "Standard age restriction compliant with COPPA regulations.",
      riskLevel: "low",
      category: "Eligibility",
    },
    {
      id: "c12",
      number: "4.1.1",
      originalText: "You retain ownership of any intellectual property rights that you hold in the content you post.",
      simplifiedText: "You still own what you post.",
      explanation: "While you retain ownership, this must be read alongside the broad license grant in clause 4.2.1.",
      riskLevel: "low",
      category: "Content Rights",
    },
  ],
  categories: [
    { name: "Data Privacy", score: 25, weight: 0.25 },
    { name: "User Rights", score: 35, weight: 0.20 },
    { name: "Company Liability", score: 20, weight: 0.20 },
    { name: "Subscription Transparency", score: 55, weight: 0.15 },
    { name: "Dispute Resolution", score: 30, weight: 0.20 },
  ],
};

export const MOCK_COMPARISON: { a: AnalysisResult; b: AnalysisResult } = {
  a: MOCK_ANALYSIS,
  b: {
    serviceName: "TikTok",
    fairnessScore: 29,
    verdict: "Very Unfair",
    totalClauses: 28,
    highRiskCount: 12,
    mediumRiskCount: 10,
    lowRiskCount: 6,
    clauses: [],
    categories: [
      { name: "Data Privacy", score: 15, weight: 0.25 },
      { name: "User Rights", score: 30, weight: 0.20 },
      { name: "Company Liability", score: 25, weight: 0.20 },
      { name: "Subscription Transparency", score: 45, weight: 0.15 },
      { name: "Dispute Resolution", score: 20, weight: 0.20 },
    ],
  },
};
